// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_DEFAULT Role = 0
	Role_ADMIN   Role = 1
)

var Role_name = map[int32]string{
	0: "DEFAULT",
	1: "ADMIN",
}

var Role_value = map[string]int32{
	"DEFAULT": 0,
	"ADMIN":   1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7fd9bf7231cc9b95, []int{0}
}

// User resource.
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []Role   `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=user.Role" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fd9bf7231cc9b95, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRoles() []Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.Role", Role_name, Role_value)
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("test/proto/user.proto", fileDescriptor_7fd9bf7231cc9b95) }

var fileDescriptor_7fd9bf7231cc9b95 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0x2d, 0x2e,
	0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03, 0x33, 0x85, 0x58,
	0x40, 0x6c, 0xa5, 0x24, 0x2e, 0x96, 0xd0, 0xe2, 0xd4, 0x22, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4,
	0xdc, 0x54, 0x09, 0x26, 0xb0, 0x08, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x9a, 0x9a, 0x9b, 0x98, 0x99,
	0x23, 0xc1, 0x0c, 0x16, 0x84, 0x70, 0x84, 0x14, 0xb8, 0x58, 0x8b, 0xf2, 0x73, 0x52, 0x8b, 0x25,
	0x58, 0x14, 0x98, 0x35, 0xf8, 0x8c, 0xb8, 0xf4, 0xc0, 0x76, 0x04, 0xe5, 0xe7, 0xa4, 0x06, 0x41,
	0x24, 0xb4, 0xe4, 0xb8, 0x58, 0x40, 0x5c, 0x21, 0x6e, 0x2e, 0x76, 0x17, 0x57, 0x37, 0xc7, 0x50,
	0x9f, 0x10, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0x56, 0x47, 0x17, 0x5f, 0x4f, 0x3f, 0x01, 0xc6, 0x24,
	0x36, 0xb0, 0x83, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0xba, 0x55, 0xa0, 0xa9, 0x00,
	0x00, 0x00,
}
